/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package log.agent;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // @Test void appHasAGreeting() {
    //     App classUnderTest = new App();
    //     // assertNotNull("app should have a greeting", classUnderTest.getGreeting()); // Method doesn't exist
    // }
}

